# Generated by Django 4.2.1 on 2023-05-30 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_student_address_remove_student_batch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.district'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.state'),
        ),
    ]
