# Generated by Django 4.2.1 on 2023-05-30 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_student_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
