# Generated by Django 4.2.1 on 2023-05-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='date',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainer',
            field=models.CharField(choices=[('neethu', 'neethu'), ('gopika', 'Gopika')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='course_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.course'),
        ),
    ]
