# Generated by Django 4.2.1 on 2023-05-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_course_remove_batch_date_batch_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='course',
        ),
    ]
