# Generated by Django 4.2 on 2023-06-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_student_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_type', models.CharField(choices=[('one_time', 'One Time'), ('two_time', 'Two Time'), ('three_time', 'Three Time')], max_length=10, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('tax', models.IntegerField(null=True)),
                ('installment_period', models.IntegerField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.course')),
            ],
        ),
    ]
