# Generated by Django 4.2 on 2023-06-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_coursefees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefees',
            name='fees_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('two_time', 'Two Time'), ('three_time', 'Three Time'), ('registration', 'Registration')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='coursefees',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
