# Generated by Django 4.2 on 2023-06-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_alter_coursefees_fees_type_alter_coursefees_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefees',
            name='tax',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
