# Generated by Django 4.2 on 2023-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_alter_coursefees_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course_details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='has_laptop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='installment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='trainer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
