# Generated by Django 4.2 on 2023-06-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_student_batch_student_course_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='installment_type',
        ),
        migrations.AddField(
            model_name='student',
            name='fees_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.coursefees'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='has_laptop',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
