# Generated by Django 4.2 on 2023-06-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_remove_student_installment_type_student_fees_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('receipt_number', models.CharField(max_length=50)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_to_account', models.CharField(choices=[('oneteam ac 1', 'Oneteam ac 1'), ('oneteam ac 2', 'Oneteam ac 2'), ('oneteam ac 3', 'Oneteam ac 3')], max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=50)),
                ('description', models.TextField()),
                ('receipt_image', models.ImageField(upload_to='receipts/')),
            ],
        ),
    ]
