# Generated by Django 4.2 on 2023-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0018_feesreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='trainer',
            field=models.CharField(choices=[('neethu', 'neethu'), ('gopika', 'Gopika')], max_length=6, null=True),
        ),
    ]
