# Generated by Django 4.2 on 2023-06-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_alter_student_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesreceipt',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.student'),
        ),
    ]
