# Generated by Django 4.2 on 2023-06-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_feesreceipt_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('one_time', 'One Time'), ('two_times', 'Two Times')], default='one_time', max_length=10)),
                ('first_pay_date', models.DateField(blank=True, null=True)),
                ('first_pay_amount', models.IntegerField(blank=True, null=True)),
                ('second_pay_date', models.DateField(blank=True, null=True)),
                ('second_pay_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
