# Generated by Django 4.2 on 2023-06-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_alter_student_selection_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Selection2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fees_type',
        ),
    ]
