# Generated by Django 4.2 on 2023-06-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_student_fees_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fees_type',
        ),
    ]
